- name: Install
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true

- name: Clone TPM
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_user_dir }}/.config/tmux/plugins/tpm"

- name: Initialize TPM and plugins
  ansible.builtin.shell: |
    "{{ ansible_user_dir }}/.config/tmux/plugins/tpm/tpm"
    "{{ ansible_user_dir }}/.config/tmux/plugins/tpm/bin/install_plugins"
