- name: "Install"
  community.general.homebrew:
    name: zsh
    state: present

- name: "Set as default"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: "Install Oh-my-posh"
  community.general.homebrew:
    name: jandedobbeleer/oh-my-posh/oh-my-posh
    state: present
