- name: Install
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true

- name: "Set {{ role_name }} as default"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: true

- name: Install Oh-my-posh
  ansible.builtin.shell: "curl -LsSf https://ohmyposh.dev/install.sh | bash -s -- -d ~/.local/bin/"
  args:
    creates: ~/.local/bin/oh-my-posh

- name: Install Zinit
  ansible.builtin.shell: "curl -LsSf https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh | bash"
