- name: Check if exists
  shell: command -v go
  register: go_exists
  ignore_errors: yes

- name: Install
  when: go_exists is failed
  become: true
  block:
  - name: Delete previous installation
    ansible.builtin.file:
      path: "{{ GOPATH }}"
      state: absent

  - name: Download binary
    ansible.builtin.get_url:
      url: "https://go.dev/dl/go{{ go_version }}.darwin-arm64.tar.gz"
      dest: "/tmp/go{{ go_version }}.darwin-arm64.tar.gz"
      mode: '0755'

  - name: "Extract tar file"
    ansible.builtin.unarchive:
      src: "/tmp/go{{ go_version }}.darwin-arm64.tar.gz"
      dest: "{{ GOPATH }}"
      force: true
      mode: "0755"

  - name: Delete downloaded tar file
    ansible.builtin.file:
      path: "/tmp/go{{ go_version }}.darwin-arm64.tar.gz"
      state: absent

