- name: "Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ansible-lint
      - ripgrep
    state: present
  become: true

- name: Check existence
  ansible.builtin.stat:
    path: /opt/nvim-linux64
  register: nvim_check

- name: Install
  when: not nvim_check.stat.exists
  block:
    - name: Download Neovim binary archive
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
        dest: /tmp/nvim-linux64.tar.gz
        mode: "0644"

    # TODO: Check current/new version
    # - name: Remove existing Neovim installation
    #   ansible.builtin.file:
    #     path: /opt/nvim-linux6
    #     state: absent
    #
    - name: Extract to /opt
      ansible.builtin.unarchive:
        src: /tmp/nvim-linux64.tar.gz
        dest: /opt/
        remote_src: yes
      become: true

    - name: Clean up downloaded archive
      ansible.builtin.file:
        path: /tmp/nvim-linux64.tar.gz
        state: absent

- name: Create symlink
  ansible.builtin.file:
    src: /opt/nvim-linux64/bin/nvim
    dest: /usr/local/bin/nvim
    state: link
  become: true
