# - name: "Dependencies"
#   ansible.builtin.apt:
#     name:
#       - build-essential
#       - libreadline-dev
#       - unzip
#     state: present
#   become: true

# TODO: Test if apt will work for Lua, if not, build from source
- name: Install Lua
  ansible.builtin.apt:
    name:
      - "lua{{ lua_version }}"
      - "liblua{{ lua_version }}-dev"
      - "luarocks"
    state: present
  become: true

# - name: Check if exists
#   shell: command -v luarocks
#   register: luarocks_exists
#   ignore_errors: yes
#
# - name: Install
#   when: luarocks_exists is failed
#   become: true
#   block:
#   - name: Delete previous installation
#     command: rm -rf /usr/local/luarocks
#
#   - name: Download binary
#     ansible.builtin.get_url:
#       url: "https://luarocks.github.io/luarocks/releases/luarocks-3.11.1.tar.gz"
#       dest: "/tmp/luarocks-3.11.1.tar.gz"
#       mode: '0755'
#
#   - name: "Extract tar file"
#     ansible.builtin.unarchive:
#       src: "/tmp/luarocks-3.11.1.tar.gz"
#       dest: "/usr/local"
#       mode: "0755"
#
#   - name: Delete downloaded tar file
#     ansible.builtin.file:
#       path: "/tmp/luarocks-3.11.1.tar.gz"
#       state: absent
