# - name: Install
#   ansible.builtin.command: curl -sSf https://sh.rustup.rs | sh -s -- -yq
#
- name: Check if exists
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y

- name: Set default compiler
  ansible.builtin.shell: |
    rustup override set stable
    rustup update stable
