- name: "Dependencies"
  ansible.builtin.apt:
    name:
      - cmake
      - g++
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - libxkbcommon-dev
    state: present
  become: true

- name: Clone latest version
  ansible.builtin.git:
    repo: https://github.com/alacritty/alacritty.git
    depth: 1
    dest: "{{ ansible_user_dir }}/.local/alacritty"
  register: alacritty_clone

- name: Build
  when: alacritty_clone.changed
  block:
    - name: Build
      ansible.builtin.shell: cargo build --release
      args:
        chdir: "{{ ansible_user_dir }}/.local/alacritty"
    - name: Add desktop icon
      ansible.builtin.shell: |
        sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
        sudo desktop-file-install extra/linux/Alacritty.desktop
        sudo update-desktop-database
      args:
        chdir: "{{ ansible_user_dir }}/.local/alacritty"

- name: Create symlink
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.local/alacritty/target/release/alacritty"
    dest: "{{ ansible_user_dir }}/.local/bin/alacritty"
    state: link
