- name: Check if Homebrew is installed
  ansible.builtin.command: command -v brew
  register: homebrew_check

- name: Install Homebrew
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | NONINTERACTIVE=1 bash -s"
  become: true
  become_user: {{ ansible_user_id }}
  when: homebrew_check.rc != 0
  notify:
    - Update Homebrew packages

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when:
    - homebrew_check.rc == 0

- name: Install Homebrew packages
  community.general.homebrew:
    name:
    - cmake
    - curl
    - pkg-config
    - libtool
    - unzip
    - ripgrep
    state: present

- name: Update Homebrew packages
  community.general.homebrew:
    upgrade_all: true
