- name: "Install"
  ansible.builtin.shell: "curl -LsSf https://sw.kovidgoyal.net/kitty/installer.sh | bash /dev/stdin"
  args:
    creates: ~/.local/kitty.app

- name: "Add to '~/.local/bin'"
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "~/.local/kitty.app/bin/kitty", dest: "~/.local/bin/kitty" }
    - { src: "~/.local/kitty.app/bin/kitten", dest: "~/.local/bin/kitten" }

#TODO: Add desktop icon - https://sw.kovidgoyal.net/kitty/binary/
