- name: "Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: Check if exists
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes

- name: Install
  when: cargo_exists is failed
  block:
  - name: Download Installer
    ansible.builtin.get_url:
      url: https://sh.rustup.rs
      dest: /tmp/sh.rustup.rs
      mode: '0755'
      force: 'yes'

  - name: Install
    shell: /tmp/sh.rustup.rs -y

  - name: Set default compiler
    ansible.builtin.shell: |
      rustup override set stable
      rustup update stable
