- name: Bootstrap development environment
  hosts: localhost
  vars:
    the_user: "{{ ansible_user_id }}"
    default_roles:
    - package_manager
    - zsh
    - fzf
    - tmux
    - neovim
    - kitty
    - fonts
    - lazygit

  tasks:
  - name: Run roles
    ansible.builtin.include_role:
      apply:
        tags:
          - "{{ roles_item }}"
      name: "{{ roles_item }}"
    loop_control:
      loop_var: roles_item
    with_items: "{{ default_roles }}"
