- name: Check if Homebrew is installed
  ansible.builtin.command: which brew
  register: homebrew_check

- name: Install Homebrew
  ansible.builtin.shell: "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh | bash -s"
  become: true
  when: homebrew_check.rc != 0
  notify:
    - Update Homebrew packages

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when:
    - homebrew_check.rc == 0

- name: Install Homebrew packages
  community.general.homebrew:
    name:
      - cmake
      - curl
      - pkg-config
      - libtool
      - unzip
      - ripgrep
    state: present

- name: Update Homebrew packages
  community.general.homebrew:
    upgrade_all: true
