- name: "Check if Homebrew is installed"
  ansible.builtin.command: which brew
  register: homebrew_check

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true
  when:
    - homebrew_check.rc == 0
  notify:
    - Update Homebrew packages

- name: Install Homebrew
  ansible.builtin.shell: /bin/sh -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/brew
  become: true
  when: homebrew_check.rc =! 0

