- name: Install
  ansible.builtin.apt:
    name:
    - python3
    - python3-pip
    - python3-venv
    state: present
  become: true

- name: Install pip packages
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - shell-gpt

- name: Create symlink
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.local/fmt/bin/fmt"
    dest: "{{ ansible_user_dir }}/.local/bin/fmt"
    state: link
    force: yes
